# Caster

Make a caster for school project.


## Base


### discription

the fist assignment is to make a base for the caster. The base's dimensions are 200 mm x 120 mm and 8 mm thick.  It has 6 holes 10 mm wide and 20 mm from the edge equally spaced along the edges.


### evidence

https://cvilleschools.onshape.com/documents/77e4b098defab6604602522c/w/31f1488f5bc8683a0a409457/e/01c825a47129b087eef90d7d


### image

![The Base of the caster](Pictures%20For%20the%20Caster/Base.png)


### reflection 

I leanred that on-shape is a very easy to use, and fast way to make objects and assemble them. I learned some shortcuts that helped me alot like

* sketching (shortcut **shift-s**)
* constructions lines (shortcut **Q**)
* dimensions (shortcut **D**)
* extruding both add and remove (shortcut key **E**)
* linear patterns (no shortcut)



---




## Mount


### Description

the second assignment is to make a Mount for the caster. the mount's dimensions are 120 mm x 120 mm x 8 mm thick. it has four wholes 10 mm wide, and are equally spaced from the corners. there is one larger whole in the center 25 mm wide.


### Evidence

https://cvilleschools.onshape.com/documents/77e4b098defab6604602522c/w/31f1488f5bc8683a0a409457/e/077d0726e76a9f0b877fbfac


### Image

![The Mount of the caster](Pictures%20For%20the%20Caster/Mount.png)


### Reflection


making the mount was relly easy. watching someone do it and then you see them and go along, makes it really easy to do the mount.




---



### Fork


### Description

the third assignment is about making a fork for the caster. it has two circles at teh top of the two forks. It is 10 mm wide the fork is 56 mm high. the circular ring of the fork is 78 mm in the diameter.


### Evidence

https://cvilleschools.onshape.com/documents/77e4b098defab6604602522c/w/31f1488f5bc8683a0a409457/e/8da632b1b09e763e5e22e9f7


### Image

![The Fork of the caster](Pictures%20For%20the%20Caster/Fork.png)


### Reflection

This was a really challenging assignment. It took lots of diminsioning (**D**), fillet(**shift-f**), extrude (**shift-e**). But I was able to do it smoothly, even though  I made some mistakes along the way.




---



## Tire


### Description

the forth assignment is about making the tire of the caster. it has a dark color. it is 80 mm in diameters, and has a 20 mm center distance. 


### Evidence

https://cvilleschools.onshape.com/documents/77e4b098defab6604602522c/w/31f1488f5bc8683a0a409457/e/c598c06a8781c818493c00cd


### Image

![The Tire of the caster](Pictures%20For%20the%20Caster/Tire.png)


### Reflection

At first I thought that this was going to be hard. But it wasn't, first I made a 2D shape that was made from a rectangle. the rectangle was revolved around the horizantle construction line to give it the circular shape. 




---




## Wheel


### Description

the fifth assignment is to make a wheel to hold the tire. it has a diametere of 80 mm. it is made up of 4 circles, 80 mm, 70 mm, 25 mm, 10 mm. 


### Evidence

https://cvilleschools.onshape.com/documents/77e4b098defab6604602522c/w/31f1488f5bc8683a0a409457/e/01c825a47129b087eef90d7d


### Image

![The wheel of the caster](Pictures%20For%20the%20Caster/Wheel.png)


### Reflection

the wheel was the hardest one so far. it took a really long time to finish, and there was lots of diminsioning (**D**), fillet (**shift-f**), and extruding (**E**)



---



## Axle,Collar


### Description

The 6th and 7th assignment is the axle and collar. it is a long tube with two flat tops that are used to hold the bottom of the screws. The flat part is 10 mm long each, the diameter of the tube is 10 mm. the diameter collar is 15 mm. 


### Evidence

https://cvilleschools.onshape.com/documents/77e4b098defab6604602522c/w/31f1488f5bc8683a0a409457/e/1f965089afcc83a9634eb144


### Image

![The Axle,Collar of the caster](Pictures%20For%20the%20Caster/Axel,Collar.png)


### Reflection
this part wasn't really hard to make. the challenging part was when you had to use the (use) part (shortcut**u**) to choose two of the sides of the collar.then use a circle (**c**), qonstruction (**q**) to make the whole in the collar.




---



## Sub Assembly


### discription 

this is the sub assembly of the caster. it has the wheel,tire,axle,bearings. the tire was mated to the wheel by the fastened mate (**m**) the axle is located at the center of the wheel, while the bearing is located in the axle.


### Evidence

https://cvilleschools.onshape.com/documents/77e4b098defab6604602522c/w/31f1488f5bc8683a0a409457/e/37c51f34ec62b8acd8a5d39a


### Image

![The sub-assembly of the caster](Pictures%20For%20the%20Caster/Sub-Assembly.png)


### Reflection
this was my first time assembling something in onshape. it seemed difficult at first looks, but onshape has made it really easy to mate and assemble things together. I used the fastened mate(**m**) to mate the wheel and the tire together. Then I used the revolved mate (**m**) to put the bearing around the axle.




---



## Final Assembly


### discription

the is the final assembly for the caster. it has bolts,nuts, and pins in the holes. This was a combination of the sub-assembly which made it easier to put all of the together. I inserted the collars, the sub-assemly, the base, and the mount to make the final product. I used revolve mate(**m**) alot to make them be able to rotate.


### Evidence

https://cvilleschools.onshape.com/documents/77e4b098defab6604602522c/w/31f1488f5bc8683a0a409457/e/a164747c2d8974a85d42aaf8


### Image

![The final-assembly of the caster](Pictures%20For%20the%20Caster/Final-Assembly.png)


### Reflection
This final assignment was a bit challenging. useing revolve mates, parallel mates, and fastened mates to put all of it together. I had to revelove(short-cut**m**) most of the parts to make them be able to rotate. I ran into some problems with the mount and the base that required me to go back and change the dimentions of the holes. The fun part was at teh end were I had to put screws in the holes of the base and the mount. the chalenging part was the sub-assembly where I also had the wronge dimentions for the fork and so I wasn't able to put the bearing in.  



---


# Dowel-pins



### Discripsion

the dowel pins are small pins that would be put in wood frames to hold them together. The dowel pins were configured so that I can use many sizes at any time.
the pins have 16 different sizes and diameters. teh lengths are (1/2 in,  1 in, 1+1/2 in, 2 in.)


### evidence

https://cvilleschools.onshape.com/documents/9a7ff9b9b55b326eb6dc8a7f/w/bc3542aa0d96cb770fa41e29/e/e5cd2882562b643f4aa680eb?configuration=List_2EDkHCiUpfIzB8%3DDefault%3BList_agcLTEd6FDKZXD%3D_2_in%3BList_dOfd1W48FPLq6l%3DDefault


### image

![dowel pins iamge ](Picture%20For%20the%20Dowel%20Pins/Dowel%20Pins.png)


### reflection

I had lots of problems with the videos for making the dowel pins. I wasn't able to make the last part and finish the dowel pins, but I was able to make the pins. It seemed hard at first. But after trying it, it was really easy. I made 16 different sizes of pins with different diameters and lenghts.



---


## frame 

### discription 

the frame of the picture frame is in the shape of a trapizoid. it is 200 mm long, and the sides are 45 degrees. It is 20 mm wide and has two holes in each side. it is also configured to be (**400 mm**) long, and (**200 mm**) short. 


### evidence

https://cvilleschools.onshape.com/documents/9a7ff9b9b55b326eb6dc8a7f/w/bc3542aa0d96cb770fa41e29/e/952c6926175b1797cc99952e?configuration=List_VBb2oCSGNBNlzM%3DDefault


### image

![Frame Part iamge ](Picture%20For%20the%20Dowel%20Pins/Frame%20Part.png)


### reflection 

this was the frame part of the whole picture frame. it was really hard to configure it, since the measurments were incorrect. I had to redimention alot of the trapezoid to the perfect amount for hte configuration ot work. I finished the frame part correctly and configured a long and a short part, and moved on to the final assembly. 



---

## final assembly


### Discription

This is the final part/ assembly for the dowel-pins assignment. it has two long frame parts (**400 mm**), and two short frame parts (**400 mm**) assembled together. it also has 8 dowel pins in total. four long pins (**2 in**) and four short pins (**1 in**) holding the frames together. 


### evidence

https://cvilleschools.onshape.com/documents/9a7ff9b9b55b326eb6dc8a7f/w/bc3542aa0d96cb770fa41e29/e/952c6926175b1797cc99952e?configuration=List_VBb2oCSGNBNlzM%3DDefault


### image

![Full picture frames iamge ](Picture%20For%20the%20Dowel%20Pins/Frame.png)


### reflection

This was the final assembly of the dowel pins. it was really easy to do, it only required revolve and fastened mates to assemble all of it. I had to redimention the holes that whould hold the dowel pins in place because it was too big. I also had to fix my frame part sketch because it wouldn't configure to the lengths needed.




---

# Cube Challenge




## cube



### discription 

The cube is the first part of the project. It is (**20 mm**) in each side. It is also extruded (**20 mm**). It has four cylinders that are (**8 mm**) in diameteres. and is extruded (**10 mm**) each.


### evidence 

[Cube](https://cvilleschools.onshape.com/documents/b7d56f85f3b228bcfed73e9b/w/7723121720388cc007797222/e/f5387873142d005ba4a46382)


### image 

![Cube iamge ](Cube%20Challenge%20Pictures/Cube.png)


### reflection

The cube was really easy to do. I made all the measurements and did the extrusions. Then made a circle that was (**8 mm**) wide and (**10 mm**) long. I used the circular pattern and added 3 more circles and then finished the cube.




---

## Spinner Shaft



### discription 

The spinner shaft is a cylinder that is cutout in the middle. it has two forks that are (**30 mm**) long. they both have holes that are (**8 mm**) in diameter. There is a cylinder at the bottm that is (**10 mm**) in diameter, and (**10 mm**) long.


### evidence

[Spinner Shaft](https://cvilleschools.onshape.com/documents/b7d56f85f3b228bcfed73e9b/w/7723121720388cc007797222/e/85ae21ad2d66923f4133e4a4)


### image 

![Spinner Shaft iamge ](Cube%20Challenge%20Pictures/Spinner%20Shaft.png)


### reflection

this was teh second part of the project, it wasn't that hard, I just made to cylinders and extruded the larger one out by (**20 mm**) and filleted the edges of the two forks and finished it.




---

## Bracket 



### discription

This is the final solo part to make in this project. It is (**110 mm**) long and has two hanldes on the and on the bottom measuring (**50 mm**) and (**30 mm**). The bracket also has another line that is (**50 mm**) long, and is tilted (**150 degrees**). It is extruded (**40 mm**) and is thickend to be(**5 mm**). It has two holes that are (**10 mm**) in diameter. 


### evidence

[Bracket](https://cvilleschools.onshape.com/documents/b7d56f85f3b228bcfed73e9b/w/7723121720388cc007797222/e/ee3cd6ceee32a3d5f68f0de1)


### image

![Bracket iamge ](Cube%20Challenge%20Pictures/Bracket.png)


### reflection 

the bracket was the hardest part for me to do. I didn't made the sketch properly to make the bottom line to be (**150 degrees**) from the bottom handle of the bracket. I had to delete the entire sketch and start by using the (**line**) feature to make the entire bracket and make the degrees and dimentions correct. 




---

## Final Assembly 



### discription

This is the final assembly of the Cube Challenge. it has all the components from before mates together. there are a total of three cylindrical mates and one revolute mate. ther is one cube and two spinner shafts. two of the cylindrical mates are connected to the cube and the other one is connected to the bottom spinner shaft. the revolute mate is connected to the top spinner shaft. 


### evidence 

[Final Assembly](https://cvilleschools.onshape.com/documents/b7d56f85f3b228bcfed73e9b/w/7723121720388cc007797222/e/2f320afb2ec45d5cd4485bab)


### image 

![Final Assembly iamge ](Cube%20Challenge%20Pictures/Final%20Assembly.png)


### reflection 

this was the final assembly for the cube challenge project. the assembly wasn't hard, but the mating was really challenging to do. there were errors showing up every time I tried to mate the spinner shafts and the cube together. I had to change each mate to remove the errors and finally finished with the assembly.




---











